const characters = [
    {
        age: 55,
        gender: 'male',
        media: ['tv', 'comic'],
        name: 'All Might',
        type: 'hero',
    },
    {
        age: 18,
        gender: 'female',
        media: ['videogame'],
        name: 'Chell',
        type: 'hero',
    },
    {
        age: 245000,
        gender: 'male',
        media: ['tv', 'movie', 'comic'],
        name: 'Doomsday',
        type: 'villain',
    },
    {
        age: Infinity,
        gender: 'male',
        media: ['comic', 'movie'],
        name: 'Dormammu',
        type: 'villain',
    },
    {
        age: Infinity,
        gender: 'male',
        media: ['tv'],
        name: 'Él',
        type: 'villain',
    },
    {
        age: 94,
        gender: 'male',
        media: ['tv', 'videogame'],
        name: 'Geralt de Rivia',
        type: 'hero',
    },
    {
        age: Infinity,
        gender: 'male',
        media: ['tv'],
        name: 'Goldar',
        type: 'villain',
    },
    {
        age: Infinity,
        gender: 'male',
        media: ['movie'],
        name: 'Hades',
        type: 'villain',
    },
    {
        age: 48,
        gender: 'male',
        media: ['tv', 'comic', 'movie', 'videogame'],
        name: 'Iron Man',
        type: 'hero',
    },
    {
        age: 78,
        gender: 'male',
        media: ['movie', 'tv'],
        name: 'Jafar',
        type: 'villain',
    },
    {
        age: 25,
        gender: 'male',
        media: ['tv', 'videogame'],
        name: 'Jeice',
        type: 'villain',
    },
    {
        age: 8,
        gender: 'female',
        media: ['tv', 'videogame'],
        name: 'Lisa Simpson',
        type: 'hero',
    },
    {
        age: 1052,
        gender: 'male',
        media: ['movie', 'tv', 'omic'],
        name: 'Loki',
        type: 'villain',
    },
    {
        age: 46,
        gender: 'female',
        media: ['movie'],
        name: 'Malefica',
        type: 'villain',
    },
    {
        age: 12,
        gender: 'female',
        media: ['videogame'],
        name: 'May',
        type: 'hero',
    },
    {
        age: 40,
        gender: 'male',
        media: ['movie', 'videogame'],
        name: 'Mr Incredible',
        type: 'hero',
    },
    {
        age: 56,
        gender: 'male',
        media: ['movie', 'comic'],
        name: 'Red Skull',
        type: 'villain',
    },
    {
        age: 15,
        gender: 'male',
        media: ['comic', 'tv'],
        name: 'Robin',
        type: 'hero',
    },
    {
        age: 25,
        gender: 'male',
        media: ['movie', 'videogame'],
        name: 'Syndrome',
        type: 'villain',
    },
    {
        age: 27,
        gender: 'male',
        media: ['tv'],
        name: 'Sportacus',
        type: 'hero',
    },
    {
        age: 8,
        gender: 'female',
        media: ['tv'],
        name: 'Stephanie',
        type: 'hero',
    },
    {
        age: 33,
        gender: 'male',
        media: ['tv', 'movie', 'comic', 'videogame'],
        name: 'Superman',
        type: 'hero',
    },
    {
        age: 43,
        gender: 'female',
        media: ['tv', 'movie', 'comic'],
        name: 'Storm',
        type: 'hero',
    },
    {
        age: Infinity,
        gender: 'male',
        media: ['tv', 'comic'],
        name: 'Trigon',
        type: 'villain',
    },
    {
        age: 2,
        gender: 'male',
        media: ['tv', 'movie', 'comic'],
        name: 'Ultron',
        type: 'villain',
    },
    {
        age: 42,
        gender: 'male',
        media: ['tv', 'movie', 'comic'],
        name: 'Venom',
        type: 'hero',
    },
    {
        age: 31,
        gender: 'male',
        media: ['movie'],
        name: 'Zurg',
        type: 'villain',
    },
];
